# Numpy Tutorials 

#### What is NumPy? 


Numpy can be used for 1d, 2D, 3D array.

### Difference Between Lists & Numpy

### Lists

- Lists are slower
- In Lists 
    - Size
    - Reference 
    - Object Type 
    - Object value 
- Insertion, Deletion, Appending, Concationation
- Contiguous Memory Benefits: 
    - SIMD Vector Processing
    - Effective Cache Utilization 
    
- a, b = [1, 3, 5], [1, 2, 3]
  a * b = Error 


### Numpy 

- Numpy arrays are fast & fixed type
- Stored as Binary values (int8, int16, int32, int64)
- Faster to read 
- Less of Bytes of Memory
- No type checking when Iterating over objects 
- Takes Contiguous Memory

-  a = np.array([1, 3, 5])
   b = np.array([1, 2, 3])
   a * b = np.array([1, 6, 15])


#### Applications of NumPy

- MATLAB Replacement 
- Plotting (Matplotlib)
- Backend (Pandas, Connect 4, Digital Photography)
- Machine Learning

In [1]:
import numpy as np 
import sys

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Get Dimentions 
a.ndim,b.ndim

(1, 2)

In [7]:
a.shape, b.shape

((3,), (2, 3))

In [8]:
# Get type & size 
a.dtype, b.dtype

(dtype('int32'), dtype('float64'))

In [9]:
c = np.array([1, 2, 3], dtype="int16")

In [13]:
c.dtype, c.itemsize

(dtype('int32'), 4)

In [14]:
a.itemsize

4

In [16]:
a.nbytes, b.nbytes

(12, 48)

### Accessing/Changing Specific Elements, rows, columns, etc.

In [17]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [18]:
print(a.shape)

(2, 7)


In [21]:
# Get a Specific element [r, c]
a[1, 5], a[1, -2]

(13, 13)

In [23]:
# Get a specific Row 
a[0, :], a[:, 2]

(array([1, 2, 3, 4, 5, 6, 7]), array([ 3, 10]))

In [25]:
# Getting a little more fancey [startindex: endindex: stepindex]
a[0, 1: 6:2], a[0, 1:-2:2]

(array([2, 4, 6]), array([2, 4]))

In [27]:
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [30]:
a[:, 2] = 5
a[:, 2] = [111, 112]
print(a)

[[  1   2 111   4   5   6   7]
 [  8   9 112  11  12  20  14]]


###### 3- D Example

In [32]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
# Get specifi element (work outside in)
b[0, 1, 1], b[:, 0, :]

(4,
 array([[1, 2],
        [5, 6]]))

In [37]:
# Replace
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing Different Types of Arrays

In [38]:
# All 0s Matrix
np.zeros((5))


array([0., 0., 0., 0., 0.])

In [39]:
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [41]:
np.ones((4, 2, 2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [43]:
np.full((2, 2), 99, dtype="float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [44]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [45]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [46]:
# Random Decimal Numbers 
np.random.rand(4, 2)

array([[0.28469459, 0.35577122],
       [0.71213753, 0.96773786],
       [0.70264296, 0.91109559],
       [0.16965633, 0.85355191]])

In [47]:
np.random.random_sample(a.shape)

array([[0.91176855, 0.81396946, 0.55012447, 0.29858797, 0.93930369,
        0.8782146 , 0.31124879],
       [0.86894551, 0.35666532, 0.61448587, 0.42938876, 0.40584551,
        0.30054888, 0.15869208]])

In [50]:
# Ramdom Integer values
np.random.randint(7, size=(3, 3))

array([[4, 4, 2],
       [6, 0, 0],
       [1, 4, 0]])

In [51]:
np.random.randint(-4, 7, size=(3, 3))

array([[ 1,  5,  3],
       [ 1,  6,  0],
       [-1,  0, -2]])

In [52]:
# IDentity  matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [56]:
output = np.ones((5, 5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [60]:
z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [62]:
output[1:-1, 1:-1] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

##### Be careful when copying arrays!!!!

In [63]:
a = np.array([1, 2, 3])
b = a
b

array([1, 2, 3])

In [64]:
b[0] = 100
print(a)

[100   2   3]


In [65]:
c = a.copy()
c

array([100,   2,   3])

In [66]:
c[0] = 1

In [67]:
c

array([1, 2, 3])

### Mathematics 

In [68]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [69]:
a + 2

array([3, 4, 5, 6])

In [70]:
a - 2

array([-1,  0,  1,  2])

In [71]:
a * 2

array([2, 4, 6, 8])

In [72]:
a /2 

array([0.5, 1. , 1.5, 2. ])

In [73]:
b = np.array([1, 0, 1, 0])
b

array([1, 0, 1, 0])

In [74]:
a + b 

array([2, 2, 4, 4])

In [75]:
a ** 2 

array([ 1,  4,  9, 16], dtype=int32)

In [76]:
# Take the sin 
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [77]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

----
##### Linear Algebra

In [80]:
a = np.ones((2, 3))
print(a)
b = np.full((3, 2), 2)
print(b)

# a * b
np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [94]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

---
### Statistics

In [84]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
np.min(stats, axis=0)

array([1, 2, 3])

In [88]:
np.max(stats, axis=0)

array([4, 5, 6])

In [90]:
np.median(stats, axis=1)

array([2., 5.])

In [93]:
np.sum(stats, axis=1), np.sum(stats)

array([ 6, 15])

---
### Reorganizing Arrays

In [96]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [97]:
after = before.reshape((8, 1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [98]:
after = before.reshape((2, 2, 2))

In [99]:
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [100]:
# after = before.reshape(2, 3)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [102]:
# Vertically Stacking Vectors 
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [104]:
# Horizantal stack 
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

--- 
### Miscellanueous 


Load data from File

In [110]:
filedata = np.genfromtxt('data.txt', delimiter=',')

filedata = filedata.astype('int32')
filedata

array([[  1,  13,  23,  33,  43,  53,  63,   6,   7,   8,   9,   2,   3,
          4,   5],
       [  1,  43,  13,  33, 768,  75,   4,  55,   4,   6,   3,   4,   5,
          6,   7]])

---
#### Boolean Masking & Advanced Indexing 

In [112]:
filedata[filedata > 50]

array([ 53,  63, 768,  75,  55])

In [113]:
## You can index with a list in NumPy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [114]:
np.any(filedata >50, axis=0)

array([False, False, False, False,  True,  True,  True,  True, False,
       False, False, False, False, False, False])

In [115]:
np.all(filedata > 50, axis=0)

array([False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False])

In [116]:
np.all(filedata > 50, axis=1)

array([False, False])

In [119]:
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True, False, False,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True]])

## Quiz

In [132]:
array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], 
                  [16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]])

In [133]:
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [134]:
array[2:4, :2]

array([[11, 12],
       [16, 17]])

In [140]:
array[[0, 1, 2, 3], [1, 2, 3, 4]]

array([ 2,  8, 14, 20])

In [149]:
array[[0, -2, -1], -2:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

---
##### Reference 
- [FreeCodeCamp Video](https://www.youtube.com/watch?v=QUT1VHiLmmI)
- [Numpy Docs](https://numpy.org/doc/stable/)